### ISSUE TITLE
0010 - Remove Tor-Specific IPC Parameters

### ISSUE THREAD

**Issue by kk-int** [Pluggable-Transports/Pluggable-Transports-spec#11]
A survey of the IPC parameters will identify and either remove or rename parameters that are specific to Tor.

https://github.com/Pluggable-Transports/Pluggable-Transports-spec/blob/master/proposals/0010%20-%20Remove%20Tor-Specific%20IPC%20Parameters.pdf

**Comment by m4mb01t4l14n0** [comment]
Recommendation from PTIM: issue a point-release of the spec (2.2.1) officially DEPRECATING these parameters.  This will serve as an initial step toward future 2.3 or 3.0 (when they're officially gone)
