### ISSUE TITLE
PT uses TOR_PT_ env variables

### ISSUE THREAD

**Issue by fortuna** [Pluggable-Transports/Pluggable-Transports-spec#2]
PT shouldn't be tied to Tor's implementation

**Comment by n8fr8** [comment]
Proposal 10 seeks to resolve this: https://github.com/Pluggable-Transports/Pluggable-Transports-spec/blob/master/proposals/0010%20-%20Remove%20Tor-Specific%20IPC%20Parameters.pdf

**Comment by blanu** [comment]
Resolved in proposal 0010 - Remove Tor-Specific IPC Parameters, which was merged into the PT v3.0 draft
