### ISSUE TITLE
Clarify use of UDP

### ISSUE THREAD

**Issue by oxtoacart** [Pluggable-Transports/Pluggable-Transports-spec#4]
The spec states that

"All transports that are currently implemented use TCP. Therefore, this proposal will focus on adding UDP application support using the existing TCP transports. This means that the Client App will send UDP packets to the PT Client, TCP packets will be sent between the obfuscation and the PT Server, and then the PT Server will send UDP packets to the Server App."

FWIW, Lantern actually uses some transports that could be candidates for becoming "Pluggable" transports which actually use UDP rather than TCP under the covers. Furthermore, in our usage, this is orthogonal to the transmission of UDP application data via that transport. That's handled at a higher layer (e.g. tun2socks plus badvpn-udpgw) and in our opinion might not need to be part of the PT spec.

**Comment by kk-int** [comment]
Language to be clarified before 2.2 spec is released.

**Comment by blanu** [comment]
Resolved in PT v3.0 draft
